import Head from "next/head";
import styles from "../styles/Home.module.css";
import InputForm from "../components/InputForm";
import TodosBox from "../components/TodosBox";
import Profile from "../components/Profile";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Todo App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Profile />
        <InputForm />
        <div className={styles.todosBox}>
          <TodosBox />
        </div>
      </main>
    </div>
  );
}
