version: "3.9"
services:
  auth:
    container_name: auth
    restart: always
    build: /Users/sandeepkumar/code/work/application/gluestack/todoapp/backend/functions/auth
    volumes:
      - /Users/sandeepkumar/code/work/application/gluestack/todoapp/backend/functions/auth:/server
      - /server/node_modules
    env_file:
      - /Users/sandeepkumar/code/work/application/gluestack/todoapp/backend/functions/auth/.env
  engine:
    container_name: engine
    restart: always
    build: /Users/sandeepkumar/code/work/application/gluestack/todoapp/backend/engine
    volumes:
      - /Users/sandeepkumar/code/work/application/gluestack/todoapp/backend/engine:/server
      - /server/node_modules
    env_file:
      - /Users/sandeepkumar/code/work/application/gluestack/todoapp/backend/engine/.env
  nginx:
    container_name: nginx
    restart: always
    build: /Users/sandeepkumar/code/work/application/gluestack/todoapp/backend/engine/router
    ports:
      - 9090:80
    volumes:
      - /Users/sandeepkumar/code/work/application/gluestack/todoapp/backend/engine/router/nginx.conf:/etc/nginx/nginx.conf
  graphql:
    container_name: graphql
    restart: always
    image: hasura/graphql-engine:v2.16.1
    ports:
      - 8080:8080
    volumes:
      - /Users/sandeepkumar/code/work/application/gluestack/todoapp/backend/functions/graphql/.db-data:/hasura
    env_file:
      - /Users/sandeepkumar/code/work/application/gluestack/todoapp/backend/functions/graphql/.env
    depends_on:
      postgres:
        condition: service_healthy
  postgres:
    container_name: postgres
    restart: always
    image: postgres:12
    ports:
      - 5433:5432
    volumes:
      - /Users/sandeepkumar/code/work/application/gluestack/todoapp/backend/databases/postgres/db:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: todo_db
    healthcheck:
      test:
        - CMD-SHELL
        - psql -U postgres -d todo_db
      interval: 10s
      timeout: 10s
      retries: 50
      start_period: 30s
